### ISSUE TITLE
Build error in Ubuntu 22.04

### ISSUE THREAD

**Issue by Romualdo-Caruso** [mariuz/flamerobin#322]
Hello,
I followed the steps outlined in https://github.com/mariuz/flamerobin/blob/master/BUILD.txt on Ubuntu 22.04 desktop. 
After running _make_ command I got the following error

~/project/flamerobin/src/gui/AdvancedSearchFrame.cpp: In member function ‘void AdvancedSearchFrame::OnListCtrlResultsItemSelected(wxListEvent&)’:
~/project/flamerobin/src/gui/AdvancedSearchFrame.cpp:459:38: error: no matching function for call to ‘wxStyledTextCtrl::StartStyling(int&)’
  459 |                 stc_ddl->StartStyling(p);
      |                 ~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ~/project/flamerobin/src/gui/AdvancedSearchFrame.cpp:30:
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note: candidate: ‘void wxStyledTextCtrl::StartStyling(int, int)’
 2640 |     void StartStyling(int pos, int mask);
      |          ^~~~~~~~~~~~
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [CMakeFiles/flamerobin.dir/build.make:384: CMakeFiles/flamerobin.dir/src/gui/AdvancedSearchFrame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/flamerobin.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`
`

Thanks in advance for any help

**Comment by Jdochoa** [comment]
Please update your version of widgets to 3.2.

./jo

**Comment by Romualdo-Caruso** [comment]
Thanks for your answer.
I'm on Ubuntu 22.04 LTS and wxWidgets version is still 3.0
Nevertheless I could build flamerobin tag 0.9.12 ( the last one that builds with wxWidgets 3.0 ) and found that one of the problems I had was corrected: Triggers are now shown in dependencies.
There is another problem still present: Trigger comments are not shown.
Is this a bug or has to do with some configuration setting ?
Thanks

**Comment by arvanus** [comment]
The thing about trigger comments not shown are a bug, please create an issue specific for it

**Comment by mariuz** [comment]
related build instructions for wxwidgets 3.2

https://github.com/mariuz/flamerobin/wiki/How-to-Build-flamerobin-on-ubuntu-or-debian

**Comment by Romualdo-Caruso** [comment]
Thanks mariuz and avarnus for your answer.
